//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFEnhanceTools.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFEnhanceTools.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AppId 无效! 请输入整数 的本地化字符串。
        /// </summary>
        internal static string AppIdIsInvalid {
            get {
                return ResourceManager.GetString("AppIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId 不存在 / 机器人可能离线 的本地化字符串。
        /// </summary>
        internal static string AppIdNotExistsOrBotOffline {
            get {
                return ResourceManager.GetString("AppIdNotExistsOrBotOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未安装 ASFEnhance 插件，请先安装 ASFEnhance 插件。 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceNotInstalled {
            get {
                return ResourceManager.GetString("ASFEnhanceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人: {0} 昵称: {1} 余额: {2} {3} SteamId: {4} 的本地化字符串。
        /// </summary>
        internal static string BotListTemplete {
            get {
                return ResourceManager.GetString("BotListTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到机器人 的本地化字符串。
        /// </summary>
        internal static string botNotFound {
            get {
                return ResourceManager.GetString("botNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接出错：{0} 的本地化字符串。
        /// </summary>
        internal static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现意外错误：{0} 的本地化字符串。
        /// </summary>
        internal static string ConnectErrorUnexpectedly {
            get {
                return ResourceManager.GetString("ConnectErrorUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败, 请检查地址和密码是否填写正确 的本地化字符串。
        /// </summary>
        internal static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接至 ASF 失败 的本地化字符串。
        /// </summary>
        internal static string ConnectToASFFailed {
            get {
                return ResourceManager.GetString("ConnectToASFFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要下单吗? 如果需要卡单请勾选【卡单模式】 的本地化字符串。
        /// </summary>
        internal static string DoYouReallyWantToPurchase {
            get {
                return ResourceManager.GetString("DoYouReallyWantToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;P. 卡单 的本地化字符串。
        /// </summary>
        internal static string FakePurchase {
            get {
                return ResourceManager.GetString("FakePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASF API地址无效 的本地化字符串。
        /// </summary>
        internal static string IPCAddressInvalid {
            get {
                return ResourceManager.GetString("IPCAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取购物车失败 的本地化字符串。
        /// </summary>
        internal static string LoadCartFailed {
            get {
                return ResourceManager.GetString("LoadCartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择机器人 的本地化字符串。
        /// </summary>
        internal static string NoBotSelected {
            get {
                return ResourceManager.GetString("NoBotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好像没有勾选任何项目 的本地化字符串。
        /// </summary>
        internal static string NotSelectedAntthing {
            get {
                return ResourceManager.GetString("NotSelectedAntthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有有效的 SubId / BundleId, 请检查输入 的本地化字符串。
        /// </summary>
        internal static string NoValidSubIdsOrBundleIds {
            get {
                return ResourceManager.GetString("NoValidSubIdsOrBundleIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;P. 购买 的本地化字符串。
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买结果: {0} 余额变动: {1} -&gt; {2} ({3}) 的本地化字符串。
        /// </summary>
        internal static string PurchaseResultTemplate1 {
            get {
                return ResourceManager.GetString("PurchaseResultTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车总价: {0} ({1}), 购物车内容: 的本地化字符串。
        /// </summary>
        internal static string PurchaseResultTemplate2 {
            get {
                return ResourceManager.GetString("PurchaseResultTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        internal static string ReadFailed {
            get {
                return ResourceManager.GetString("ReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
